// <auto-generated />
using System;
using Garage_Management.Base.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_Management.Base.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304060036_AddPolicy")]
    partial class AddPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.AppointmentSparePart", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "SparePartId");

                    b.HasIndex("SparePartId");

                    b.ToTable("AppointmentSpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Đường Láng, Đống Đa, Hà Nội",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5283),
                            FirstName = "Nguyễn Văn",
                            LastName = "An",
                            UserId = 10
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5285),
                            FirstName = "Trần Thị",
                            LastName = "Bình",
                            UserId = 11
                        });
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5173),
                            EmployeeCode = "NV-ADMIN-001",
                            FirstName = "Nguyễn Văn",
                            IsActive = true,
                            LastName = "Admin",
                            Position = "Quản trị hệ thống",
                            StartWorkingDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5177),
                            EmployeeCode = "QL-001",
                            FirstName = "Trần Thị",
                            IsActive = true,
                            LastName = "Quản",
                            Position = "Quản lý gara",
                            StartWorkingDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5180),
                            EmployeeCode = "KT-001",
                            FirstName = "Lê Văn",
                            IsActive = true,
                            LastName = "Hùng",
                            Position = "Kỹ thuật viên",
                            StartWorkingDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(5182),
                            EmployeeCode = "LT-001",
                            FirstName = "Phạm Thị",
                            IsActive = true,
                            LastName = "Lan",
                            Position = "Lễ tân",
                            StartWorkingDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed2fde03cb5846d4aa69e14c72039211",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 33, 770, DateTimeKind.Utc).AddTicks(1157),
                            Email = "admin@garage.vn",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GARAGE.VN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECjlHv3DiHwe2AvMCwH9e/hHqv4bb5Z514+LgYEyO3oNHDhlUQFKb+ft1v7LLga2zg==",
                            PhoneNumber = "0909123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e9064c08-df3a-452e-a0f5-81ab4290a2af",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0133430593f43c9833d4c4110ec29ec",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 33, 823, DateTimeKind.Utc).AddTicks(2525),
                            Email = "manager01@garage.vn",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER01@GARAGE.VN",
                            NormalizedUserName = "SUPERVISOR01",
                            PasswordHash = "AQAAAAIAAYagAAAAEHSgs0rHXRVkZYh7QPlwnQrj3oXqXIQnIbSxKmgTrQPEAtTawq7g1H83Tq222gqSAQ==",
                            PhoneNumber = "0912345678",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5ceebc9e-3a4e-4614-9e8e-e2ae8c6b10ac",
                            TwoFactorEnabled = false,
                            UserName = "Supervisor01"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8828b6bb15684792988cc7f50db90f44",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 33, 877, DateTimeKind.Utc).AddTicks(5739),
                            Email = "mechanic01@garage.vn",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MECHANIC01@GARAGE.VN",
                            NormalizedUserName = "MECHANIC01",
                            PasswordHash = "AQAAAAIAAYagAAAAEKn1sbBfP/TmqiKtBOyOwHlDrle2H1L2NVYs7VQWczV3JK6CSKqm2v+1QhuBSQb+QQ==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bc636c98-ab16-47ca-a8a9-6faeb912d571",
                            TwoFactorEnabled = false,
                            UserName = "mechanic01"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f659ee099560487582df77ec68b8fbb1",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 33, 931, DateTimeKind.Utc).AddTicks(6398),
                            Email = "reception@garage.vn",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RECEPTION@GARAGE.VN",
                            NormalizedUserName = "RECEP01",
                            PasswordHash = "AQAAAAIAAYagAAAAEKHXzADSk35gnfFAzyWejcnPeh9V6qPWhPo4VT+7bYVYGmYAQ+60KSM+CO8tWX02tQ==",
                            PhoneNumber = "0978123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "462f92c2-3f01-4369-95f5-07210a3b7518",
                            TwoFactorEnabled = false,
                            UserName = "recep01"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf9429dd4a5642be8d252c1cf7e42765",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 33, 990, DateTimeKind.Utc).AddTicks(8878),
                            Email = "stocker@garage.vn",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STOCKER@GARAGE.VN",
                            NormalizedUserName = "STOCKER01",
                            PasswordHash = "AQAAAAIAAYagAAAAEIAQ/nUZsvxDY8RhteQaJcQAggwkpXWqTnErdmd0oo4r7g/efI7xui0DDtpKlylHcg==",
                            PhoneNumber = "0978123356",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a7d856ca-eb9d-4946-bb11-63d1e911239a",
                            TwoFactorEnabled = false,
                            UserName = "stocker01"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1ae3002628f419f9507f792b8a22764",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 45, DateTimeKind.Utc).AddTicks(4003),
                            Email = "nguyen.van.a@gmail.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYEN.VAN.A@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG01",
                            PasswordHash = "AQAAAAIAAYagAAAAEHG7Sz83O4cshzzidiV6VHTIuV3onqLiul8WfzHq016RMf0vf96HiUctZkPn6PCyrw==",
                            PhoneNumber = "0912345670",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c938f6ac-be53-4457-a76b-4eaeab7c1930",
                            TwoFactorEnabled = false,
                            UserName = "khachhang01"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f15f1c4bee1f44a0a9bf399f923eca7d",
                            CreatedAt = new DateTime(2026, 3, 4, 6, 0, 34, 108, DateTimeKind.Utc).AddTicks(4659),
                            Email = "tran.thi.b@gmail.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TRAN.THI.B@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG02",
                            PasswordHash = "AQAAAAIAAYagAAAAELTMcW8C7L8COSZKbYM1yHI1yiwZc+zvu8oLqMKk8pdENwJPSk6xy3yTHNrAcOiV3g==",
                            PhoneNumber = "0987654312",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "27608f83-7580-496c-a05b-0eaf4a580b27",
                            TwoFactorEnabled = false,
                            UserName = "khachhang02"
                        });
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.Inventory", b =>
                {
                    b.Property<int>("SparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModelCompatible")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SparePartBrandId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SparePartId");

                    b.HasIndex("SparePartBrandId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.SparePartBrand", b =>
                {
                    b.Property<int>("SparePartBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartBrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SparePartBrandId");

                    b.ToTable("SparePartBrands");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.StockTransaction", b =>
                {
                    b.Property<int>("StockTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StockTransactionId");

                    b.HasIndex("SparePartId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ServiceTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SparePartTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("JobCardId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCard", b =>
                {
                    b.Property<int>("JobCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCardId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkBayId")
                        .HasColumnType("int");

                    b.HasKey("JobCardId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WorkBayId");

                    b.ToTable("JobCards");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardLog", b =>
                {
                    b.Property<int>("JobCardLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCardLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UserEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserIdEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("JobCardLogId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("UserEmployeeId");

                    b.HasIndex("UserIdEmployeeId");

                    b.ToTable("JobCardLogs");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardMechanic", b =>
                {
                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobCardId", "EmployeeId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("JobCardMechanics");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardService", b =>
                {
                    b.Property<int>("JobCardServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCardServiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceInspectionItemId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("JobCardServiceId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("ServiceId");

                    b.ToTable("JobCardServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardServiceTask", b =>
                {
                    b.Property<int>("JobCardServiceTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCardServiceTaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<int?>("JobCardServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskOrder")
                        .HasColumnType("int");

                    b.HasKey("JobCardServiceTaskId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("JobCardServiceId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("ServiceTaskId");

                    b.ToTable("JobCardServiceTasks");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardSparePart", b =>
                {
                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUnderWarranty")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JobCardId", "SparePartId");

                    b.HasIndex("SparePartId");

                    b.ToTable("JobCardSpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.WorkBay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobcardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobcardId");

                    b.ToTable("WorkBay");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimate", b =>
                {
                    b.Property<int>("RepairEstimateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairEstimateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ServiceTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SparePartTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RepairEstimateId");

                    b.HasIndex("JobCardId");

                    b.ToTable("RepairEstimates");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimateService", b =>
                {
                    b.Property<int>("RepairEstimateId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RepairEstimateId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RepairEstimateServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimateSparePart", b =>
                {
                    b.Property<int>("RepairEstimateId")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RepairEstimateId", "SparePartId");

                    b.HasIndex("SparePartId");

                    b.ToTable("RepairEstimateSpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ServiceWarrantyPolicyPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceWarrantyPolicyPolicyId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.ServiceTask", b =>
                {
                    b.Property<int>("ServiceTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTaskId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("EstimateMinute")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaskOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ServiceTaskId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceTasks");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.ServiceWarrantyPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("MileageLimit")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.ToTable("ServiceWarrantyPolicies");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.VehicleBrand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BrandId");

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.VehicleModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.SparePartWarrantyPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("MileageLimit")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.ToTable("SparePartWarrantyPolicies");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.WarrantyService", b =>
                {
                    b.Property<int>("WarrantyServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyServiceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceWarrantyPolicyId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceWarrantyPolicyPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WarrantyServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceWarrantyPolicyId");

                    b.HasIndex("ServiceWarrantyPolicyPolicyId");

                    b.ToTable("WarrantyServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.WarrantySparePart", b =>
                {
                    b.Property<int>("WarrantySparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantySparePartId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<int>("SparePartWarrantyPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WarrantySparePartId");

                    b.HasIndex("SparePartId");

                    b.HasIndex("SparePartWarrantyPolicyId");

                    b.ToTable("WarrantySpareParts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Receptionist",
                            NormalizedName = "RECEPTIONIST"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mechanic",
                            NormalizedName = "MECHANIC"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stocker",
                            NormalizedName = "STOCKER"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Appointment", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", null)
                        .WithMany("CreatedAppointments")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Garage_Management.Base.Entities.Vehiclies.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.AppointmentService", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Appointment", "Appointment")
                        .WithMany("Services")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Services.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.AppointmentSparePart", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Appointment", "Appointment")
                        .WithMany("SpareParts")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Inventories.Inventory", "Inventory")
                        .WithMany("AppointmentSpareParts")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Customer", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "User")
                        .WithOne()
                        .HasForeignKey("Garage_Management.Base.Entities.Accounts.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Employee", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "User")
                        .WithOne()
                        .HasForeignKey("Garage_Management.Base.Entities.Accounts.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.User", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.Inventory", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Inventories.SparePartBrand", "SparePartBrand")
                        .WithMany("SpareParts")
                        .HasForeignKey("SparePartBrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SparePartBrand");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.StockTransaction", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Inventories.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Invoice", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithOne("Invoice")
                        .HasForeignKey("Garage_Management.Base.Entities.Invoice", "JobCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCard", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Appointment", "Appointment")
                        .WithMany("GeneratedJobCards")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Customer", "Customer")
                        .WithMany("JobCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", null)
                        .WithMany("CreatedJobCards")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "Supervisor")
                        .WithMany("SupervisedJobCards")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Garage_Management.Base.Entities.Vehiclies.Vehicle", "Vehicle")
                        .WithMany("JobCards")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.JobCards.WorkBay", null)
                        .WithMany("JobCardHistory")
                        .HasForeignKey("WorkBayId");

                    b.Navigation("Appointment");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("Supervisor");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardLog", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany("Logs")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "User")
                        .WithMany()
                        .HasForeignKey("UserEmployeeId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "UserId")
                        .WithMany()
                        .HasForeignKey("UserIdEmployeeId");

                    b.Navigation("JobCard");

                    b.Navigation("User");

                    b.Navigation("UserId");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardMechanic", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "Employee")
                        .WithMany("AssignedJobCards")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany("Mechanics")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Employee");

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardService", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany("Services")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Services.Service", "Service")
                        .WithMany("JobCardServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobCard");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardServiceTask", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany()
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCardService", null)
                        .WithMany("ServiceTasks")
                        .HasForeignKey("JobCardServiceId");

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Employee", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById");

                    b.HasOne("Garage_Management.Base.Entities.Services.ServiceTask", "ServiceTask")
                        .WithMany("JobCardServiceTasks")
                        .HasForeignKey("ServiceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobCard");

                    b.Navigation("PerformedBy");

                    b.Navigation("ServiceTask");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardSparePart", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany("SpareParts")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Inventories.Inventory", "Inventory")
                        .WithMany("JobCardSpareParts")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.WorkBay", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany()
                        .HasForeignKey("JobcardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Notification", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimate", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.JobCards.JobCard", "JobCard")
                        .WithMany("Estimates")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimateService", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimate", "RepairEstimate")
                        .WithMany("Services")
                        .HasForeignKey("RepairEstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Services.Service", "Service")
                        .WithMany("RepairEstimateServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RepairEstimate");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimateSparePart", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimate", "RepairEstimate")
                        .WithMany("SpareParts")
                        .HasForeignKey("RepairEstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Inventories.Inventory", "Inventory")
                        .WithMany("RepairEstimateSpareParts")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("RepairEstimate");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.Service", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Services.ServiceWarrantyPolicy", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceWarrantyPolicyPolicyId");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.ServiceTask", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Services.Service", "Service")
                        .WithMany("ServiceTasks")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.Vehicle", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Vehiclies.VehicleBrand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Accounts.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Vehiclies.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Customer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.VehicleModel", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Vehiclies.VehicleBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.WarrantyService", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Services.Service", "Service")
                        .WithMany("WarrantyServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Services.ServiceWarrantyPolicy", "ServiceWarrantyPolicy")
                        .WithMany()
                        .HasForeignKey("ServiceWarrantyPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Services.ServiceWarrantyPolicy", null)
                        .WithMany("WarrantyServices")
                        .HasForeignKey("ServiceWarrantyPolicyPolicyId");

                    b.Navigation("Service");

                    b.Navigation("ServiceWarrantyPolicy");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.WarrantySparePart", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Inventories.Inventory", "Inventory")
                        .WithMany("WarrantySpareParts")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Warranties.SparePartWarrantyPolicy", "SparePartWarrantyPolicy")
                        .WithMany("WarrantySpareParts")
                        .HasForeignKey("SparePartWarrantyPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("SparePartWarrantyPolicy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Garage_Management.Base.Entities.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Appointment", b =>
                {
                    b.Navigation("GeneratedJobCards");

                    b.Navigation("Services");

                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("JobCards");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Employee", b =>
                {
                    b.Navigation("AssignedJobCards");

                    b.Navigation("CreatedAppointments");

                    b.Navigation("CreatedJobCards");

                    b.Navigation("SupervisedJobCards");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Accounts.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.Inventory", b =>
                {
                    b.Navigation("AppointmentSpareParts");

                    b.Navigation("JobCardSpareParts");

                    b.Navigation("RepairEstimateSpareParts");

                    b.Navigation("WarrantySpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Inventories.SparePartBrand", b =>
                {
                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCard", b =>
                {
                    b.Navigation("Estimates");

                    b.Navigation("Invoice");

                    b.Navigation("Logs");

                    b.Navigation("Mechanics");

                    b.Navigation("Services");

                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.JobCardService", b =>
                {
                    b.Navigation("ServiceTasks");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.JobCards.WorkBay", b =>
                {
                    b.Navigation("JobCardHistory");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.RepairEstimaties.RepairEstimate", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.Service", b =>
                {
                    b.Navigation("AppointmentServices");

                    b.Navigation("JobCardServices");

                    b.Navigation("RepairEstimateServices");

                    b.Navigation("ServiceTasks");

                    b.Navigation("WarrantyServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.ServiceTask", b =>
                {
                    b.Navigation("JobCardServiceTasks");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Services.ServiceWarrantyPolicy", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("WarrantyServices");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("JobCards");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.VehicleBrand", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Vehiclies.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Garage_Management.Base.Entities.Warranties.SparePartWarrantyPolicy", b =>
                {
                    b.Navigation("WarrantySpareParts");
                });
#pragma warning restore 612, 618
        }
    }
}
