# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - msmg-api-fpt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Garage_Management.API/Garage_Management.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Garage_Management.API/Garage_Management.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE8B553B3D5F476D9FDF0124FACEA27F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79D6B680CBE44D878A76E94D43F2AE5F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4949FD57960641D6AF2B6E7EEA5C290F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'msmg-api-fpt'
          slot-name: 'Production'
          package: .

      - name: Set deployment metadata env vars
        uses: azure/appservice-settings@v1
        with:
          app-name: 'msmg-api-fpt'
          app-settings-json: |
            [
              {
                "name": "GIT_COMMIT_SHA",
                "value": "${{ github.sha }}",
                "slotSetting": false
              },
              {
                "name": "BUILD_TIME",
                "value": "${{ github.event.head_commit.timestamp }}",
                "slotSetting": false
              },
              {
                "name": "APP_VERSION",
                "value": "${{ github.run_number }}",
                "slotSetting": false
              }
            ]
          